# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build openssl
    runs-on: ubuntu-latest
    env:
      OPENSSL_VERSION: 3.0.14

    steps:
    - name: Install build tools
      run: sudo apt-get install build-essential gcc-mingw-w64 binutils-mingw-w64 mingw-w64 curl pkg-config osslsigncode
    - name: Download openssl ${{ env.OPENSSL_VERSION }}
      run: mkdir openssl && curl -L -s https://github.com/openssl/openssl/archive/refs/tags/openssl-$OPENSSL_VERSION.tar.gz | tar xvfz - -C openssl --strip-components=1
      working-directory: /tmp
    - name: Build and Install openssl ${{ env.OPENSSL_VERSION }}
      run: |
        ./Configure mingw64 -static no-asm --prefix=/usr/src --cross-compile-prefix=x86_64-w64-mingw32-
        make clean && make && sudo make install
      working-directory: /tmp/openssl
    - name: Sign openssl file
      env:
        PKCS12_FILE: ${{ secrets.PKCS12_FILE }}
        PKCS12_PASS: ${{ secrets.PKCS12_PASS }}
      run: |
        echo $PKCS12_FILE | base64 --decode > PKCS12.pfx
        osslsigncode sign -pkcs12 PKCS12.pfx -pass $PKCS12_PASS -h sha256 -n "OpenSSL" -i https://github.com/mailsvb/openssl/ -t http://timestamp.digicert.com -in /usr/src/bin/openssl.exe -out /tmp/openssl.exe
        tar -cJf openssl.tar.xz openssl.exe
      working-directory: /tmp
    - name: Create GitHub release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.OPENSSL_VERSION }}
        release_name: OpenSSL release ${{ env.OPENSSL_VERSION }}
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: /tmp/openssl.tar.xz
        asset_name: openssl.tar.xz
        asset_content_type: application/x-xz
