# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build openssl
    runs-on: ubuntu-latest

    steps:
    - name: Install build tools
      run: sudo apt-get install build-essential gcc-mingw-w64 binutils-mingw-w64 mingw-w64 curl pkg-config
    - name: Download openssl
      run: mkdir openssl && curl -L -s https://github.com/openssl/openssl/archive/refs/tags/openssl-3.0.1.tar.gz | tar xvfz - -C openssl --strip-components=1
      working-directory: /tmp
    - name: Build and Install openssl
      run: |
        ./Configure mingw64 -static no-asm --prefix=/usr/src --cross-compile-prefix=x86_64-w64-mingw32-
        make clean && make && sudo make install
      working-directory: /tmp/openssl
    - name: check libs
      run: ls -lah
      working-directory: /usr/src/bin
